### ISSUE TITLE
[V2] Listeners go into a Matched state even without matching Connectors

### ISSUE THREAD

**Issue by bartoval** [skupperproject/skupper#1734] opened 2024-10-18 07:48 UTC
This is a behavior that occurs when I **delete** a V2 Skupper application (including CRs) and then I recreate it.
PS: If I then restart Skupper controller, listeners go into **Configured** state which is correct.
Example:
Connectors CRs are empty
![empty-conn](https://github.com/user-attachments/assets/0e0a33f4-a4c2-4f3b-b3a9-48ce671e1560)

![lsiteners](https://github.com/user-attachments/assets/8641b327-f595-4282-b8dd-0fb4fa904621)

**Comment by grs** [comment] 2024-10-21 12:40
This is a duplicate of #1643

**Closed** 2024-10-21 14:01 UTC
