### ISSUE TITLE
bridge-server error with http2 traffic

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper#137] opened 2020-07-24 17:24 UTC
Encountered with skupper-example-grpc (product catalog service):

2020-07-24T17:19:18.254Z bridge-server info Ingress sending request for 1 (21 bytes)
stream: adjusting kept idle streams num_idle_streams=0, max=100
recv: connection recv_window_size=21, local_window=65535
stream: adjusting kept idle streams num_idle_streams=0, max=100
recv: [IB_READ_HEAD]
recv: payloadlen=4, type=3, flags=0x00, stream_id=1
recv: RST_STREAM
recv: [IB_READ_NBYTE]
recv: readlen=4, payloadleft=0, left=0
stream: stream(0x564c021520e8)=1 close
stream: destroy closed stream(0x564c021520e8)=1
stream: dep_remove stream(0x564c021520e8)=1
stream: adjusting kept idle streams num_idle_streams=0, max=100
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error [ERR_HTTP2_INVALID_STREAM]: The stream has been destroyed
    at ServerHttp2Stream.respond (internal/http2/core.js:2454:13)
    at IngressStream.on_message (/opt/app-root/lib/http2.js:285:21)
    at Ingress.on_message (/opt/app-root/lib/http2.js:133:16)
    at Receiver.emit (events.js:198:13)
    at Receiver.link.dispatch (/opt/app-root/node_modules/rhea/lib/link.js:59:37)
    at Incoming.on_transfer (/opt/app-root/node_modules/rhea/lib/session.js:361:22)
    at Session.on_transfer (/opt/app-root/node_modules/rhea/lib/session.js:749:19)
    at Connection.(anonymous function) [as on_transfer] (/opt/app-root/node_modules/rhea/lib/connection.js:809:30)
    at c.dispatch (/opt/app-root/node_modules/rhea/lib/types.js:910:33)
    at Transport.read (/opt/app-root/node_modules/rhea/lib/transport.js:109:36)
Emitted 'error' event at:
    at Container.dispatch (/opt/app-root/node_modules/rhea/lib/container.js:41:33)
    at Connection.dispatch (/opt/app-root/node_modules/rhea/lib/connection.js:261:40)
    at Connection.input (/opt/app-root/node_modules/rhea/lib/connection.js:561:18)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by grs** [comment] 2020-07-29 10:08
Duplicate of https://github.com/skupperproject/skupper-proxy/issues/10

**Closed** 2020-10-19 13:25 UTC
