### ISSUE TITLE
Updating Skupper from 0.8.X to 0.8.6 breaks most connections

### ISSUE THREAD

**Issue by Kampe** [skupperproject/skupper#685] opened 2022-03-08 16:36 UTC
Hello!

We recently rolled the latest bugfix version of skupper and have found that our routers no longer stay connected for very long after the upgrade and subsequent roll of all the services to the latest releases.

Some namespace' service controller logs are filled with:

```
Failed to update default/skupper-internal: Operation cannot be fulfilled on configmaps "skupper-internal": the object has been modified; please apply your changes to the latest version and try again
```

While some are completely crashing on the edge sites:
```
2022-03-07T17:55:01.459716428Z stderr F E0307 17:55:01.458706       1 service_sync.go:273] Failed reading message from service sync EOF
2022-03-07T17:54:58.833369836Z stderr F 2022/03/07 17:54:58 Started workers
2022-03-07T17:54:58.633096277Z stderr F 2022/03/07 17:54:58 Console server listening on :8080
2022-03-07T17:54:58.432714333Z stderr F 2022/03/07 17:54:58 Starting workers
2022-03-07T17:54:58.332647803Z stderr F 2022/03/07 17:54:58 Waiting for informer caches to sync
2022-03-07T17:54:58.332592583Z stderr F 2022/03/07 17:54:58 Starting the Skupper controller
2022-03-07T17:54:53.321007763Z stderr F 2022/03/07 17:54:53 Waiting for Skupper router component to start
2022-03-07T17:54:53.314603333Z stderr F 2022/03/07 17:54:53 Setting up event handlers
2022-03-07T17:54:53.288709639Z stderr F 2022/03/07 17:54:53 Version: 0.8.6
2022-03-07T17:54:53.288654769Z stderr F 2022/03/07 17:54:53 Skupper service controller
2022-03-07T17:53:19.591033217Z stderr F 	/go/src/app/cmd/service-controller/controller.go:309 +0x479
2022-03-07T17:53:19.591028021Z stderr F created by main.(*Controller).Run
2022-03-07T17:53:19.59102298Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88 +0x4d
2022-03-07T17:53:19.591018451Z stderr F k8s.io/apimachinery/pkg/util/wait.Until(0xc00044a080, 0x3b9aca00, 0xc0000ac660)
2022-03-07T17:53:19.591014077Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153 +0xf8
2022-03-07T17:53:19.591007581Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00044a080, 0x3b9aca00, 0x0, 0x1, 0xc0000ac660)
2022-03-07T17:53:19.590999788Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152 +0x5e
2022-03-07T17:53:19.590986582Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00044a080)
2022-03-07T17:53:19.590978151Z stderr F 	/go/src/app/cmd/service-controller/controller.go:550 +0x2b
2022-03-07T17:53:19.590957857Z stderr F main.(*Controller).runServiceCtrl(0xc00038a4b0)
2022-03-07T17:53:19.590952945Z stderr F 	/go/src/app/cmd/service-controller/controller.go:841 +0x79
2022-03-07T17:53:19.59094493Z stderr F main.(*Controller).processNextEvent(0xc00038a4b0, 0x1)
2022-03-07T17:53:19.590940176Z stderr F 	/go/src/app/cmd/service-controller/controller.go:740 +0x1ba
2022-03-07T17:53:19.590934336Z stderr F main.(*Controller).processNextEvent.func1(0xc00038a4b0, 0x14c82c0, 0xc0002f8700, 0x0, 0x0)
2022-03-07T17:53:19.590926772Z stderr F 	/go/src/app/cmd/service-controller/controller.go:575 +0x596
2022-03-07T17:53:19.590919763Z stderr F main.(*Controller).updateBridgeConfig(0xc00038a4b0, 0xc0006586c8, 0x1b, 0x1, 0x0)
2022-03-07T17:53:19.590913667Z stderr F 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
2022-03-07T17:53:19.59090786Z stderr F panic(0x15354e0, 0x2400630)
2022-03-07T17:53:19.590889074Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:55 +0x105
2022-03-07T17:53:19.590883564Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2022-03-07T17:53:19.590877401Z stderr F goroutine 30 [running]:
2022-03-07T17:53:19.590870564Z stderr F 
2022-03-07T17:53:19.590864908Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13bc876]
2022-03-07T17:53:19.590852891Z stderr F 	panic: runtime error: invalid memory address or nil pointer dereference
2022-03-07T17:53:19.590795741Z stderr F panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2022-03-07T17:53:19.588176888Z stderr F 	/go/src/app/cmd/service-controller/controller.go:309 +0x479
2022-03-07T17:53:19.58816875Z stderr F created by main.(*Controller).Run
2022-03-07T17:53:19.588159228Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88 +0x4d
2022-03-07T17:53:19.588150395Z stderr F k8s.io/apimachinery/pkg/util/wait.Until(0xc00044a080, 0x3b9aca00, 0xc0000ac660)
2022-03-07T17:53:19.588143548Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153 +0xf8
2022-03-07T17:53:19.588135895Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00044a080, 0x3b9aca00, 0x0, 0x1, 0xc0000ac660)
2022-03-07T17:53:19.588128093Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152 +0x5e
2022-03-07T17:53:19.588120118Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00044a080)
2022-03-07T17:53:19.588113457Z stderr F 	/go/src/app/cmd/service-controller/controller.go:550 +0x2b
2022-03-07T17:53:19.588105498Z stderr F main.(*Controller).runServiceCtrl(0xc00038a4b0)
2022-03-07T17:53:19.588096734Z stderr F 	/go/src/app/cmd/service-controller/controller.go:841 +0x79
2022-03-07T17:53:19.588089714Z stderr F main.(*Controller).processNextEvent(0xc00038a4b0, 0x1)
2022-03-07T17:53:19.588081538Z stderr F 	/go/src/app/cmd/service-controller/controller.go:740 +0x1ba
2022-03-07T17:53:19.58806568Z stderr F main.(*Controller).processNextEvent.func1(0xc00038a4b0, 0x14c82c0, 0xc0002f8700, 0x0, 0x0)
2022-03-07T17:53:19.588058581Z stderr F 	/go/src/app/cmd/service-controller/controller.go:575 +0x596
2022-03-07T17:53:19.588050166Z stderr F main.(*Controller).updateBridgeConfig(0xc00038a4b0, 0xc0006586c8, 0x1b, 0x1, 0x0)
2022-03-07T17:53:19.588041002Z stderr F 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
2022-03-07T17:53:19.588032801Z stderr F panic(0x15354e0, 0x2400630)
2022-03-07T17:53:19.588024365Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:48 +0x82
2022-03-07T17:53:19.588016321Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2022-03-07T17:53:19.588007213Z stderr F 	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:74 +0xa3
2022-03-07T17:53:19.587997979Z stderr F k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15354e0, 0x2400630)
2022-03-07T17:53:19.587983084Z stderr F goroutine 30 [running]:
2022-03-07T17:53:19.587918001Z stderr F E0307 17:53:19.587709       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```

We rolled the latest versions of skupper and most connections looked to be functioning normally for us, given some time we start to see the failures accrue.   

I know how to fix this by just clean-slating, but on upgrade are we to expected to delete the entire certificate chain for all connected sites?

**Comment by Kampe** [comment] 2022-03-08 18:12
There's only a singular router in each "skuppered" namespace, as well as a singular service controller.

`quay.io/skupper/service-controller:0.8.6` on the service controller, router running `quay.io/interconnectedcloud/qdrouterd:1.17.1`

**Comment by grs** [comment] 2022-03-08 18:14
Does the single skupper-router pod have two container in it though? or just one?

**Comment by Kampe** [comment] 2022-03-08 18:43
it has two containers, one being the config-sync and one being the router

**Comment by grs** [comment] 2022-03-08 18:45
Are there any errors in logs from the config-sync container?

**Comment by Kampe** [comment] 2022-03-08 18:47
So, I've started peeking at different environments, and some do not have a config-sync container on the routers (the ones I have not completely gutted by deleting skupper-site and replacing the certificates)

**Comment by grs** [comment] 2022-03-08 19:07
Ok, that was my suspicion on the cause of the router connectivity, i.e. that the deployments are not being updated to have the config-sync container, so the routers get stale with regard to defined services. I'll look into that and get back to you shortly.

**Comment by Kampe** [comment] 2022-03-08 19:55
that sounds pretty accurate, thanks for your work and quick response!

**Comment by grs** [comment] 2022-03-09 16:44
I've pushed a 0.8.7 release that contains fixes to ensure the config-sync sidecar is added on upgrading and also reaslied the issue with the service controller stack trace and fixed that. (Not quite sure why the configmap was not there, but the crash should be fixed at least).

Let me know how you get on with this release when you are able.

**Closed** 2022-03-10 05:46 UTC
