### ISSUE TITLE
Creating subgroups

### ISSUE THREAD

**Issue by nicob87** [skupperproject/skupper#369] opened 2021-01-11 18:08 UTC
based on  this POC:
https://github.com/skupperproject/skupper/pull/358
Create subgroups, in the same way kubectl does...
specific subgroups structure will be provided in this issue:

TODO fllme

**Comment by ajssmith** [comment] 2021-01-12 20:50
Duplicate of #370

**Closed by ajssmith** 2021-01-12 20:50 UTC
Labels: cli-changes
